[mypy]
python_version = 3.10
files = .
exclude = (?x)(^\.venv/|^tmp/)
check_untyped_defs = True
ignore_missing_imports = True
show_error_codes = True
pretty = False
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True

[mypy-tests.*]
allow_untyped_defs = True
